### ISSUE TITLE
No "to do" items / check boxes are coming over with the next daily note

### ISSUE THREAD

**Issue by yeders** [shichongrui/obsidian-rollover-daily-todos#3]
Hi there,

* I've installed / activated your plugin
* Added "## To do" to my daily note template
* selected 'To do' from your plugin settings
* yesterday, I had items on the list under the To Do header list, both directly under and under ### sublevel headings
* delete today's note if it was there
* clicked on today's note, creating a new one
* checkboxes/ todos didn't come across

Let me know what other details you require.

**Comment by ms3056** [comment]
I'm also unable to get this to function.

**Comment by daytang** [comment]
me too！

**Comment by OliverAndrews** [comment]
The API for Obsidian looks like it changed the way the filesystem works. Going through the code, this code will not run in new Obsidian API system. I have made update code [here](https://github.com/OliverAndrews/ObsidianIris). Feel free to use and let me know of bugs.

**Comment by yeders** [comment]
Hi @OliverAndrews  - any luck? I've tried the latest version and it doesn't seem to be behaving. What's your experience?

**Comment by Liquidmantis** [comment]
Huh, I'm Obsidian 0.10.8 and it works fine for me.  My heading is just `## TODOs` though, maybe the space in the words is causing parsing issues?

**Comment by OliverAndrews** [comment]
@yeders If you can open issue on repository, I will try and see!

**Comment by anitaposch** [comment]
Hi, 
I installed the plugin on Obsidian 0.10.8 (Windows 10) today. It does not rollover open todos for me too.

**Comment by tgrosinger** [comment]
While this is not a fix for this plugin, I have added the ability to roll incomplete tasks over to the current daily note in the latest release of [Slated](https://github.com/tgrosinger/slated-obsidian). Hopefully that helps tide some people over until the author of this plugin can update 🙂

**Comment by visualcurrent** [comment]
I've recently discovered and installed it on obsidian-0.11.0 and it doesn't do any roll-overs. I don't have any headings set in my template.
Nice idea though. Hope it gets fixed.

**Comment by Fastpoopoo** [comment]
I think I have found the issue, this plugin uses the default Date() function, this means that the timezone isn't synced with your computer and if you are more than 5+ hours off from UTC, it will think that you are on the wrong timezone.

**Comment by iwaldrop-gsn** [comment]
the date issue above could certainly cause an edge-case issue, but for me the issue was that I was using a section heading and the code expects a newline and my section heading was on the last line. the code should be fixed to not expect a newline in the heading, but rather insert it if not present.

at any rate, my solution was to simply add a line after my section heading in the template

**Comment by OliverAndrews** [comment]
> the date issue above could certainly cause an edge-case issue, but for me the issue was that I was using a section heading and the code expects a newline and my section heading was on the last line. the code should be fixed to not expect a newline in the heading, but rather insert it if not present.
> 
> at any rate, my solution was to simply add a line after my section heading in the template

This is good discovery! I will take a look at the code and try to add in this change.

**Comment by Conmy** [comment]
@iwaldrop-gsn I have tried this with a newling after the heading and it still does not function for me. I am also situated and have my PC set up in GMT (same as UTC) and still have this problem.

**Comment by iwaldrop-gsn** [comment]
@Conmy I'm sorry to hear that. I'm not sure if you're comfortable digging into the code, but I just did a bit of debugging on my end to find out where execution stopped. In my case, it was getting all the way through, but not finding the heading; this lead me to inspecting the `heading` value and noticing it included the newline character.

**Comment by RyanMalaspina** [comment]
Hi, I am also running into this issue. One thing I've noticed is if I don't restart Obsidian on the next day, todos don't rollover when I click the today's daily note button. If I do restart Obsidian and click today's daily note (and today's doesn't exist yet) the todos will rollover.

**Comment by samxsmith** [comment]
I've opened a PR that resolves this issue, here:
https://github.com/shichongrui/obsidian-rollover-daily-todos/pull/11

**Comment by TomLingham** [comment]
In my case this was caused by `Date.toISOString()` [returning the date UTC](https://github.com/shichongrui/obsidian-rollover-daily-todos/blob/master/index.js#L51), which prevents the note being created as I'm in Australia I create my daily note before the date roles over in UTC.

Pull request here https://github.com/shichongrui/obsidian-rollover-daily-todos/pull/12

**Comment by shichongrui** [comment]
Sorry for the lack of response on this thread. My life has been extremely busy lately but I'd like to get these PRs merged. #11 has one approval on it, if one more person could test that PR and approve it I will merge it and get a release out. Likewise, once it is merged if we could get 2 people to test #12 I will get it merged and a release out. Thanks for your patience everyone, and sorry this has taken so long.

**Comment by ericaxu** [comment]
@shichongrui Seems like #11 is ready to go? 3 days ago there was another approval on it. Good luck with everything!

**Comment by AlansCodeLog** [comment]
So I've had a bit of time to test the PRs. Did not work at all for me so I downloaded it and poked around and there's several problems.

1. For some reason my file created date is always a few ***MINUTES*** earlier than the current date. For #11 I had to increase `MAX_TIME_SINCE_CREATION` a LOT. I have no idea why that is but the problem seems to be on Obsidian's side. But given that fix only used 5 seconds then maybe it's not a problem for other people and changing it would cause issues. 

2. If there are files that parse to invalid dates (my years have an emoji in them like 2021📅) the sort function doesn't understand them and causes the files to be sorted wrong. They need to be filtered out like:
```js
.filter(file => file.basename != null && !isNaN(new Date(file.basename).getTime()))
// also getTime is not needed in the line after, u can just do
.sort((a, b) => new Date(b.basename) - new Date(a.basename));
```
3. Or ideally, the name should be parsed given the daily file name template, but that is probably very complicated, so maybe some note that the file names should parse to valid dates?

4. Also #12 straight up does not work because the function is misnamed. I fixed that and it seems to still work for me, but then things worked for me without that fix. I'd have to investigate what it was fixing.

**Comment by TomLingham** [comment]
Thanks @AlansCodeLog. I apologise for that error with #12. Snap name-change decision at the last second that I didn't test before pushing 😓  I've updated my branch.

To give you an explanation for what #12 is fixing, [this line in master](https://github.com/shichongrui/obsidian-rollover-daily-todos/blob/master/index.js#L51) is getting the datetime in ISO8601, taking only the date portion (discarding the time), and then comparing that the date on the newly created Daily Notes file, and if it's not a match returning early and not running the plugin. It ends up looking something like this once resolved:

```javascript
// file.basename is the current date in yyyy-mm-dd
if ("2021-05-26" !== file.basename) return;
```

However, `.toISOString()` returns the date with the timezone [always zero UTC offset](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) so that date comparison will always happen between a date in UTC and the date in the users locale (`file.basename`). I'm in Australia, so that code won't run until after 11am when UTC is the same date as here.

I hope that makes sense — thanks again for picking up my silly mistake.

**Comment by shichongrui** [comment]
Both #11 and #12 are merged and a new version 1.0.2 has been released.

@AlansCodeLog I merged despite your findings only because it seems as though the PRs seemed to fix things for the most part and so I would welcome any additional PRs to further improve the plugin/harden the logic.
